DROP DATABASE IF EXISTS simli_test;

CREATE DATABASE simli_test;

USE simli_test;

CREATE TABLE user (
  id INT(10) UNIQUE NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(64) UNIQUE NOT NULL,
  password_hash VARCHAR(512) NOT NULL,
  name VARCHAR(32) NOT NULL,
  phone_number VARCHAR(32),
  birth VARCHAR(32),
  address VARCHAR(64)
);

CREATE TABLE test_answer (
  id INT UNIQUE NOT NULL AUTO_INCREMENT PRIMARY KEY,
  result_id INT NOT NULL,
  user_id int NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE RESTRICT ON DELETE CASCADE
);